# Generated by Django 5.2.17 on 2026-08-12 07:47

import apps.products.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_processing_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('white', 'White background'), ('interior', 'Interior'), ('human', 'Human')], max_length=20)),
                ('image', models.ImageField(upload_to=apps.products.models.product_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='products.productimage')),
            ],
            options={
                'ordering': ('mode',),
                'constraints': [models.UniqueConstraint(fields=('source_image', 'mode'), name='unique_generated_image_mode')],
            },
        ),
    ]
