# Generated by Django 5.2.17 on 2026-08-12

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_productgeneratedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                    ("deactivated", "Deactivated"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productgeneratedimage",
            name="image",
            field=models.ImageField(
                upload_to=apps.products.models.generated_image_upload_to,
            ),
        ),
    ]
