# Generated by Django 5.2.17 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_productvariant_color_hex_and_materials"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deactivation_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
