# Generated by Django 5.2.17 on 2026-08-13 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_deactivation_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean_jv',
            field=models.CharField(blank=True, db_index=True, max_length=14, validators=[django.core.validators.RegexValidator(message='Use an EAN containing 8 to 14 digits.', regex='^\\d{8,14}$')]),
        ),
        migrations.AddField(
            model_name='product',
            name='ean_xl',
            field=models.CharField(blank=True, db_index=True, max_length=14, validators=[django.core.validators.RegexValidator(message='Use an EAN containing 8 to 14 digits.', regex='^\\d{8,14}$')]),
        ),
    ]
