# Generated by Django 5.2.17 on 2026-08-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_type_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='otto_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='otto_category_group_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='otto_category_group_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='otto_category_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='otto_category_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
