# Generated by Django 5.2.17 on 2026-08-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_make_product_price_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='processing_claimed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='processing_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
