# Generated by Django 5.2.17 on 2026-09-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('eur_to_usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('eur_to_try', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(default='frankfurter', max_length=32)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-fetched_at',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_city',
            field=models.CharField(choices=[('IST', 'Istanbul'), ('ANK', 'Ankara'), ('IZM', 'Izmir'), ('BUR', 'Bursa'), ('KSY', 'Kars'), ('INE', 'Inegol')], default='INE', max_length=3),
        ),
    ]
