# Generated by Django 5.2.17 on 2026-09-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0025_productsetpart"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="material_composition",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional textile composition, for example 100% Polyester.",
                max_length=200,
            ),
        ),
    ]
