# Generated by Django 5.2.17 on 2026-09-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_image_thumbnails'),
        ('products', '0027_productimage_xl_cover'),
    ]

    operations = [
    ]
