# Generated by Django 5.2.17 on 2026-10-01 03:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_merge_20260930_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='listing_price_eur_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productgeneratedimage',
            name='mode',
            field=models.CharField(choices=[('white', 'White background'), ('interior', 'Interior'), ('human', 'Human'), ('xl_cover', 'XL white background')], max_length=20),
        ),
    ]
