# Generated by Django 5.2.17 on 2026-08-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0004_productgeneratedimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EanCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=14, unique=True)),
                (
                    "account",
                    models.CharField(
                        choices=[("jv", "JV"), ("xl", "XL")],
                        max_length=2,
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_ean_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ean_codes",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "indexes": [
                    models.Index(
                        fields=["account", "product"],
                        name="ean_account_product_idx",
                    ),
                ],
            },
        ),
    ]
