# Generated by Django 5.2.17 on 2026-08-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ean', '0002_release_eans_from_unapproved_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='eancode',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eancode',
            name='state',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('consumed', 'Consumed')], default='available', max_length=16),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model(
                "ean",
                "EanCode",
            ).objects.filter(product__isnull=False).update(
                state="reserved",
            ),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
