# Generated by Django 5.2.17 on 2026-08-19 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ean', '0003_eancode_consumed_at_eancode_state'),
        ('products', '0013_productimage_processing_claimed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eancode',
            index=models.Index(condition=models.Q(('product__isnull', True), ('state', 'available')), fields=['account', 'id'], name='ean_available_account_idx'),
        ),
    ]
