from django.urls import path

from .views import (
    ManagerApproveProductView,
    ManagerApproveSellerChangesView,
    ManagerChangeProductStatusView,
    ManagerCreatePriceNegotiationView,
    ManagerDashboardView,
    ManagerDeactivateProductView,
    ManagerProductListView,
    ManagerRejectProductView,
    ManagerRejectSellerChangesView,
    ManagerRequestProductAvailabilityView,
    ManagerSendProductNotificationView,
    ManagerSendTestProductSoldView,
    ProductModerationHistoryView,
)

app_name = "moderation"

urlpatterns = [
    path(
        "products/<int:product_pk>/moderation-history/",
        ProductModerationHistoryView.as_view(),
        name="product-moderation-history",
    ),
    path(
        "manager/dashboard/",
        ManagerDashboardView.as_view(),
        name="manager-dashboard",
    ),
    path(
        "manager/products/",
        ManagerProductListView.as_view(),
        name="manager-product-list",
    ),
    path(
        "manager/products/<int:product_pk>/approve/",
        ManagerApproveProductView.as_view(),
        name="manager-product-approve",
    ),
    path(
        "manager/products/<int:product_pk>/reject/",
        ManagerRejectProductView.as_view(),
        name="manager-product-reject",
    ),
    path(
        "manager/products/<int:product_pk>/status/",
        ManagerChangeProductStatusView.as_view(),
        name="manager-product-status",
    ),
    path(
        "manager/products/<int:product_pk>/seller-changes/approve/",
        ManagerApproveSellerChangesView.as_view(),
        name="manager-product-seller-changes-approve",
    ),
    path(
        "manager/products/<int:product_pk>/seller-changes/reject/",
        ManagerRejectSellerChangesView.as_view(),
        name="manager-product-seller-changes-reject",
    ),
    path(
        "manager/products/<int:product_pk>/notifications/",
        ManagerSendProductNotificationView.as_view(),
        name="manager-product-notification",
    ),
    path(
        "manager/products/<int:product_pk>/availability-request/",
        ManagerRequestProductAvailabilityView.as_view(),
        name="manager-product-availability-request",
    ),
    path(
        "manager/products/<int:product_pk>/test-sold-notification/",
        ManagerSendTestProductSoldView.as_view(),
        name="manager-product-test-sold-notification",
    ),
    path(
        "manager/products/<int:product_pk>/price-negotiation/",
        ManagerCreatePriceNegotiationView.as_view(),
        name="manager-product-price-negotiation",
    ),
    path(
        "manager/products/<int:product_pk>/deactivate/",
        ManagerDeactivateProductView.as_view(),
        name="manager-product-deactivate",
    ),
]
