# Generated by Django 5.2.17 on 2026-08-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='preffered_language',
            new_name='preferred_language',
        ),
    ]
