from django.shortcuts import get_object_or_404
from drf_spectacular.utils import (
    OpenApiParameter,
    OpenApiTypes,
    extend_schema,
)
from rest_framework import generics, status
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.common.permissions import IsManager, IsSeller, is_manager
from apps.common.throttles import (
    ImageUploadRateThrottle,
    ManagerMutationThrottleMixin,
)
from apps.idempotency.services import (
    IdempotencyKeyReuseError,
    IdempotencyRequestInProgressError,
    abandon_idempotency_claim,
    claim_idempotency_key,
    complete_idempotency_claim,
)
from apps.orchestrator.models import MarketplacePublication

from .filters import filter_products
from .models import Product, ProductImage
from .permissions import CanAccessProduct
from .serializers import (
    ProductAvailabilitySerializer,
    ProductImageReorderSerializer,
    ProductImageSerializer,
    ProductImageUploadSerializer,
    ProductSerializer,
)
from .services import (
    confirm_product_availability,
    delete_product_image,
    make_product_image_primary,
    reorder_product_images,
    request_product_deactivation,
    request_product_image_processing,
    upload_product_image,
    withdraw_product_submission,
)

IDEMPOTENCY_KEY_HEADER = OpenApiParameter(
    name="Idempotency-Key",
    type=OpenApiTypes.STR,
    location=OpenApiParameter.HEADER,
    required=False,
    description=(
        "Unique UUID generated by the client for one create request. "
        "Repeating the same request with the same key returns the original "
        "response instead of creating a duplicate product."
    ),
)


def get_editable_product_for_user(*, user, product_id: int) -> Product:
    return get_object_or_404(
        Product.objects.filter(
            pk=product_id,
            owner=user,
            status__in=(
                Product.Status.DRAFT,
                Product.Status.REJECTED,
            ),
        )
    )


class ProductListCreateView(generics.ListCreateAPIView):
    serializer_class = ProductSerializer

    def get_permissions(self):
        if self.request.method == "POST":
            return [IsAuthenticated(), IsSeller()]

        return [IsAuthenticated()]

    def get_queryset(self):
        queryset = Product.objects.select_related("owner").prefetch_related(
            "variants",
            "images",
            "images__generated_images",
        )

        if not is_manager(self.request.user):
            queryset = queryset.filter(owner=self.request.user)

        queryset = queryset.exclude(status=Product.Status.ARCHIVED)

        return filter_products(
            queryset=queryset,
            query_params=self.request.query_params,
        )

    @extend_schema(
        parameters=[
            OpenApiParameter(
                name="search",
                type=OpenApiTypes.STR,
                required=False,
                description="Case-insensitive search in the product title.",
            ),
            OpenApiParameter(
                name="status",
                type=OpenApiTypes.STR,
                required=False,
                description="Product status, for example draft or approved.",
            ),
            OpenApiParameter(
                name="product_type",
                type=OpenApiTypes.STR,
                required=False,
                description="Exact seller-entered product type.",
            ),
            OpenApiParameter(
                name="color_hex",
                type=OpenApiTypes.STR,
                required=False,
                description="Variant colour in #RRGGBB format.",
            ),
            OpenApiParameter(
                name="material",
                type=OpenApiTypes.STR,
                required=False,
                description="Exact material value within a product variant.",
            ),
            OpenApiParameter(
                name="is_available",
                type=OpenApiTypes.BOOL,
                required=False,
                description="Filter by current availability: true or false.",
            ),
            OpenApiParameter(
                name="ordering",
                type=OpenApiTypes.STR,
                required=False,
                description=(
                    "One of created_at, -created_at, updated_at, -updated_at, "
                    "title, -title."
                ),
            ),
        ],
        description=(
            "Lists the seller's own non-archived products. Managers and admins "
            "receive all non-archived products."
        ),
    )
    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    @extend_schema(
        parameters=[IDEMPOTENCY_KEY_HEADER],
        description=(
            "Создаёт товар продавца. Передайте Idempotency-Key, чтобы "
            "повторный запрос из мобильной сети не создал дубликат."
        ),
    )
    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

    @extend_schema(
        parameters=[IDEMPOTENCY_KEY_HEADER],
        description=(
            "Creates a seller product. Supply Idempotency-Key to protect "
            "against duplicate mobile requests."
        ),
    )
    def create(self, request, *args, **kwargs):
        try:
            claim = claim_idempotency_key(request=request, endpoint="products:create")
        except IdempotencyKeyReuseError:
            return Response(
                {
                    "detail": (
                        "This Idempotency-Key was already used with"
                        "different request data"
                    )
                },
                status=422,
            )

        except IdempotencyRequestInProgressError:
            return Response(
                {
                    "detail": (
                        "A request with this Idempotency-Key is still"
                        "being processed. Retry shortly with the same key"
                    )
                },
                status=status.HTTP_409_CONFLICT,
            )

        if claim.is_replay:
            return Response(claim.replay_body, status=claim.replay_status)

        try:
            response = super().create(request, *args, **kwargs)
        except Exception:
            abandon_idempotency_claim(claim=claim)
            raise

        complete_idempotency_claim(
            claim=claim,
            response_status=response.status_code,
            response_body=response.data,
        )

        return response


class ProductDetailView(
    ManagerMutationThrottleMixin,
    generics.RetrieveUpdateDestroyAPIView,
):
    # PATCH is deliberately the sole update verb: product forms send only
    # changed fields, and keeping PUT would expose an equivalent endpoint
    # with different "full replacement" expectations.
    http_method_names = ["get", "patch", "delete", "head", "options"]
    serializer_class = ProductSerializer
    permission_classes = [IsAuthenticated, CanAccessProduct]

    def get_queryset(self):
        queryset = Product.objects.select_related("owner").prefetch_related(
            "variants",
            "images",
            "images__generated_images",
        )

        if not is_manager(self.request.user):
            queryset = queryset.filter(owner=self.request.user)

        return queryset.exclude(status=Product.Status.ARCHIVED)

    def perform_destroy(self, instance):
        if not is_manager(self.request.user) and instance.status not in {
            Product.Status.DRAFT,
            Product.Status.REJECTED,
        }:
            from rest_framework.exceptions import ValidationError

            raise ValidationError(
                {
                    "detail": (
                        "Use withdraw for submitted products or deactivate "
                        "for approved products."
                    )
                }
            )

        active_publications = instance.marketplace_publications.exclude(
            status__in=(
                MarketplacePublication.Status.DEACTIVATED,
                MarketplacePublication.Status.DELETED,
                MarketplacePublication.Status.FAILED,
            )
        )

        if active_publications.exists():
            from rest_framework.exceptions import ValidationError

            raise ValidationError(
                {
                    "detail": (
                        "Deactivate or delete all active marketplace listings "
                        "before archiving this product."
                    )
                }
            )

        instance.status = Product.Status.ARCHIVED
        instance.save(update_fields=("status", "updated_at"))


class ProductImageUploadView(APIView):
    permission_classes = [IsAuthenticated, IsSeller]
    parser_classes = [MultiPartParser, FormParser]
    throttle_classes = [ImageUploadRateThrottle]

    @extend_schema(
        request=ProductImageUploadSerializer,
        responses={201: ProductImageSerializer},
    )
    def post(self, request, product_pk: int):
        product = get_editable_product_for_user(
            user=request.user,
            product_id=product_pk,
        )

        serializer = ProductImageUploadSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        image = upload_product_image(
            product=product,
            image_file=serializer.validated_data["image"],
            is_primary=serializer.validated_data["is_primary"],
        )

        return Response(
            ProductImageSerializer(image, context={"request": request}).data,
            status=status.HTTP_201_CREATED,
        )


class ProductImageDeleteView(APIView):
    permission_classes = [IsAuthenticated, IsSeller]

    @extend_schema(request=None, responses={204: None})
    def delete(self, request, product_pk: int, image_pk: int):
        product = get_editable_product_for_user(
            user=request.user,
            product_id=product_pk,
        )
        image = get_object_or_404(
            ProductImage,
            pk=image_pk,
            product=product,
        )

        delete_product_image(product=product, image=image)

        return Response(status=status.HTTP_204_NO_CONTENT)


class ProductImagePrimaryView(APIView):
    permission_classes = [IsAuthenticated, IsSeller]

    @extend_schema(request=None, responses={200: ProductImageSerializer})
    def post(self, request, product_pk: int, image_pk: int):
        product = get_editable_product_for_user(
            user=request.user,
            product_id=product_pk,
        )
        image = get_object_or_404(
            ProductImage,
            pk=image_pk,
            product=product,
        )

        image = make_product_image_primary(
            product=product,
            image=image,
        )

        return Response(
            ProductImageSerializer(image, context={"request": request}).data
        )


class ProductImageReorderView(APIView):
    permission_classes = [IsAuthenticated, IsSeller]

    @extend_schema(request=ProductImageReorderSerializer, responses={204: None})
    def post(self, request, product_pk: int):
        product = get_editable_product_for_user(
            user=request.user,
            product_id=product_pk,
        )

        serializer = ProductImageReorderSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        reorder_product_images(
            product=product,
            image_ids=serializer.validated_data["image_ids"],
        )

        return Response(status=status.HTTP_204_NO_CONTENT)


class ProductAvailabilityView(APIView):
    permission_classes = [IsAuthenticated, IsSeller]

    @extend_schema(
        request=ProductAvailabilitySerializer,
        responses={200: ProductSerializer},
    )
    def post(self, request, product_pk: int):
        product = get_object_or_404(
            Product,
            pk=product_pk,
            owner=request.user,
        )
        serializer = ProductAvailabilitySerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        product = confirm_product_availability(
            product=product,
            is_available=serializer.validated_data["is_available"],
        )
        return Response(ProductSerializer(product, context={"request": request}).data)


class ProductImageProcessView(ManagerMutationThrottleMixin, APIView):
    permission_classes = [IsManager]

    @extend_schema(request=None, responses={202: ProductImageSerializer})
    def post(self, request, product_pk: int, image_pk: int):
        product = get_object_or_404(
            Product.objects.exclude(status=Product.Status.ARCHIVED),
            pk=product_pk,
        )
        image = get_object_or_404(
            ProductImage,
            id=image_pk,
            product=product,
        )
        image = request_product_image_processing(
            product=product,
            image=image,
        )
        return Response(
            ProductImageSerializer(
                image,
                context={"request": request},
            ).data,
            status=status.HTTP_202_ACCEPTED,
        )


class ProductDeactivateView(APIView):
    """Seller submits a deactivation request; a manager confirms it later."""

    permission_classes = [IsAuthenticated, IsSeller]

    @extend_schema(request=None, responses={202: ProductSerializer})
    def post(self, request, product_pk: int):
        product = get_object_or_404(
            Product.objects.exclude(status=Product.Status.ARCHIVED),
            pk=product_pk,
            owner=request.user,
        )
        from apps.accounts.models import User
        from apps.notifications.models import Notification
        from apps.notifications.services import create_notification

        product = request_product_deactivation(product=product)
        from django.db.models import Q

        managers = User.objects.filter(
            Q(
                role__in=(
                    User.Role.MANAGER,
                    User.Role.ADMIN,
                )
            )
            | Q(is_superuser=True)
        )
        for manager in managers.distinct():
            create_notification(
                user=manager,
                sender=request.user,
                product=product,
                notification_type=Notification.Type.PRODUCT_DEACTIVATION_REQUESTED,
                title="Deactivation requested",
                body=f"Seller requested deactivation for '{product.title}'.",
                data={"product_id": product.id},
            )

        return Response(
            ProductSerializer(product, context={"request": request}).data,
            status=status.HTTP_202_ACCEPTED,
        )


class ProductWithdrawView(APIView):
    permission_classes = [IsAuthenticated, IsSeller]

    @extend_schema(request=None, responses={204: None})
    def post(self, request, product_pk: int):
        product = get_object_or_404(
            Product,
            pk=product_pk,
            owner=request.user,
        )
        withdraw_product_submission(product=product)
        return Response(status=status.HTTP_204_NO_CONTENT)
