# Generated by Django 5.2.17 on 2026-08-13 08:19
# ruff: noqa: RUF012

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_product_ean_jv_product_ean_xl'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoodProductSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('jv', 'JV'), ('xl', 'XL')], max_length=2)),
                ('ean', models.CharField(db_index=True, max_length=14)),
                ('payload', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood_snapshots', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'account'), name='unique_hood_snapshot_product_account')],
            },
        ),
    ]
