upstream django_backend {
    server web:8000;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 12m;

    location ^~ /static/ {
        alias /staticfiles/;
        access_log off;
        expires 30d;
    }

    location ~ ^/api/(docs|scalar|schema)/?$ {
        auth_basic "Benim Depom API documentation";
        auth_basic_user_file /etc/nginx/secrets/.htpasswd;

        proxy_pass http://django_backend;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $http_x_real_ip;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;

        proxy_read_timeout 180s;
        proxy_connect_timeout 30s;
    }

    location / {
        proxy_pass http://django_backend;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $http_x_real_ip;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;

        proxy_read_timeout 180s;
        proxy_connect_timeout 30s;
    }
}