# Generated by Django 5.2.17 on 2026-09-11 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0021_productvariant_color_name"),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterbuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('jv', 'JV'), ('xl', 'XL')], db_index=True, max_length=2)),
                ('afterbuy_order_id', models.CharField(db_index=True, max_length=32)),
                ('marketplace', models.CharField(choices=[('otto', 'OTTO'), ('hood', 'Hood'), ('kaufland', 'Kaufland'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('payment_method', models.CharField(blank=True, max_length=80)),
                ('platform_order_number', models.CharField(blank=True, max_length=80)),
                ('buyer_name', models.CharField(blank=True, max_length=160)),
                ('buyer_email', models.CharField(blank=True, max_length=254)),
                ('buyer_platform_user_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'afterbuy_order_id'), name='afterbuy_order_account_id_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AfterbuyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=80)),
                ('afterbuy_item_id', models.CharField(blank=True, max_length=32)),
                ('anr', models.CharField(blank=True, max_length=64)),
                ('product_id', models.CharField(blank=True, max_length=64)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('ean', models.CharField(blank=True, max_length=14)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('platform_name', models.CharField(blank=True, max_length=80)),
                ('marketplace', models.CharField(choices=[('otto', 'OTTO'), ('hood', 'Hood'), ('kaufland', 'Kaufland'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('platform_order_number', models.CharField(blank=True, max_length=80)),
                ('extra_tags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afterbuy_order_items', to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='afterbuy.afterbuyorder')),
            ],
        ),
        migrations.CreateModel(
            name='AfterbuySaleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_notification', to='afterbuy.afterbuyorderitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='afterbuyorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'item_key'), name='afterbuy_order_item_key_uniq'),
        ),
    ]
