# Generated by Django 5.2.17 on 2026-09-17 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afterbuy", "0001_initial"),
        ("products", "0023_pricenegotiation"),
    ]

    operations = [
        migrations.AddField(
            model_name='afterbuyorderitem',
            name='followup_reconciled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='AfterbuyChannelStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('jv', 'JV'), ('xl', 'XL')], max_length=2)),
                ('marketplace', models.CharField(choices=[('otto', 'OTTO'), ('hood', 'Hood'), ('kaufland', 'Kaufland'), ('other', 'Other')], max_length=16)),
                ('quantity', models.PositiveIntegerField()),
                ('observed_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afterbuy_channel_stocks', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'account', 'marketplace'), name='afterbuy_channel_stock_uniq')],
            },
        ),
    ]
