# Generated by Django 5.2.17 on 2026-08-19 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=16)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='idempotency_status_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'endpoint', 'key'), name='unique_user_endpoint_idempotency_key')],
            },
        ),
    ]
