# Generated by Django 5.2.17 on 2026-08-13 07:12
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_product_deactivation_requested_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('search', 'Search'), ('publish', 'Publish'), ('update', 'Update')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('requested_channels', models.JSONField(default=list)),
                ('request_payload', models.JSONField(default=dict)),
                ('results', models.JSONField(default=list)),
                ('error', models.JSONField(default=dict)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_jobs', to='products.product')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', 'created_at'], name='marketplace_job_product_idx'), models.Index(fields=['status', 'created_at'], name='marketplace_job_status_idx')],
            },
        ),
    ]
