# Generated by Django 5.2.17 on 2026-08-14 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
        ('products', '0010_product_otto_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplacePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('otto', 'OTTO'), ('hood', 'Hood'), ('kaufland', 'Kaufland')], max_length=16)),
                ('account', models.CharField(choices=[('jv', 'JV'), ('xl', 'XL')], max_length=2)),
                ('ean', models.CharField(db_index=True, max_length=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('publishing', 'Publishing'), ('active', 'Active'), ('deactivating', 'Deactivating'), ('deactivated', 'Deactivated'), ('deleting', 'Deleting'), ('deleted', 'Deleted'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_request', models.JSONField(blank=True, default=dict)),
                ('last_response', models.JSONField(blank=True, default=dict)),
                ('last_error', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='orchestrator.marketplacejob')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_publications', to='products.product')),
            ],
            options={
                'ordering': ('marketplace', 'account', 'id'),
                'indexes': [models.Index(fields=['product', 'status'], name='market_pub_product_state_idx'), models.Index(fields=['marketplace', 'account', 'status'], name='market_pub_channel_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'marketplace', 'account'), name='unique_product_marketplace_account')],
            },
        ),
    ]
