# Generated by Django 5.2.17 on 2026-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0003_alter_marketplacejob_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacejob',
            name='operation',
            field=models.CharField(choices=[('search', 'Search'), ('publish', 'Publish'), ('update', 'Update'), ('delete', 'Delete'), ('deactivate', 'Deactivate'), ('activate', 'Activate')], max_length=16),
        ),
    ]
