# Generated by Django 5.2.17 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestrator", "0007_marketplacecontentgeneration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplacecontentgeneration",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("partial", "Partial"),
                ],
                db_index=True,
                default="queued",
                max_length=16,
            ),
        ),
    ]
