# Generated by Django 5.2.17 on 2026-08-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0008_alter_marketplacecontentgeneration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacepublication',
            name='status_before_operation',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('publishing', 'Publishing'), ('active', 'Active'), ('deactivating', 'Deactivating'), ('deactivated', 'Deactivated'), ('deleting', 'Deleting'), ('deleted', 'Deleted'), ('failed', 'Failed')], default='', help_text='Stable status before an in-progress marketplace operation. Used to restore the listing if the external request fails.', max_length=16),
        ),
    ]
