# Generated by Django 5.2.17 on 2026-08-11 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('product_approved', 'Product approved'), ('product_rejected', 'Product rejected'), ('product_confirmation', 'Product confirmation'), ('image_processing_completed', 'Image processing completed'), ('image_processing_failed', 'Image processing failed'), ('message_received', 'Message received'), ('product_availability_reminder', 'Product availability reminder'), ('manager_message', 'Manager message')], max_length=50),
        ),
    ]
