# Generated by Django 5.2.17 on 2026-08-19 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_product_deactivation_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('invalid', 'Invalid device token')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='notifications.devicetoken')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='notifications.notification')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['status', 'updated_at'], name='push_delivery_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'device_token'), name='unique_notification_push_delivery')],
            },
        ),
    ]
