# Generated by Django 5.2.17 on 2026-08-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_pushdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('invalid', 'Invalid device token')], db_index=True, default='pending', max_length=16),
        ),
    ]
